table ColorFormats
	lineageTag: 459b3dfe-da52-4ee0-a10e-7b248dd1bd3c

	column Column1
		dataType: string
		lineageTag: a8b79107-13fd-41bf-a7e3-2ea31b6688b8
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: abcd739f-0ac5-4dd2-868b-e5a19c0a06fe
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 8178ad8e-14ed-413c-9a97-cd1ece135603
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition ColorFormats = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Student\Downloads\01-prepare-data\ColorFormats.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

