table ResellerSalesTargets
	lineageTag: fc05aa02-32da-45a3-a497-78e97999d244

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5c519f95-44b0-4863-ac4c-e8195d00216a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: 7552db63-13e7-4c1c-8e70-ee51dcd1066d
		summarizeBy: count
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column M01
		dataType: string
		lineageTag: 39ae1edc-61f0-45d9-bb7d-1649c8470b16
		summarizeBy: none
		sourceColumn: M01

		annotation SummarizationSetBy = Automatic

	column M02
		dataType: string
		lineageTag: 3c123148-d5dc-4f84-843f-ac8195860ef5
		summarizeBy: none
		sourceColumn: M02

		annotation SummarizationSetBy = Automatic

	column M03
		dataType: string
		lineageTag: 69445cb2-bc89-4420-8cc8-eaee4bfd6d53
		summarizeBy: none
		sourceColumn: M03

		annotation SummarizationSetBy = Automatic

	column M04
		dataType: string
		lineageTag: 90bf6bff-75d9-48c5-abc7-c1fe9d59a17d
		summarizeBy: none
		sourceColumn: M04

		annotation SummarizationSetBy = Automatic

	column M05
		dataType: string
		lineageTag: 17b96178-f5e9-411c-bb39-f4c071d806c2
		summarizeBy: none
		sourceColumn: M05

		annotation SummarizationSetBy = Automatic

	column M06
		dataType: string
		lineageTag: d917f97c-1c60-4f3e-a621-10742e3643b7
		summarizeBy: none
		sourceColumn: M06

		annotation SummarizationSetBy = Automatic

	column M07
		dataType: string
		lineageTag: d70c54ee-c795-42fb-8680-fe7b099d2bfe
		summarizeBy: none
		sourceColumn: M07

		annotation SummarizationSetBy = Automatic

	column M08
		dataType: string
		lineageTag: 55dce9b4-a769-4630-91af-470bf55028c3
		summarizeBy: none
		sourceColumn: M08

		annotation SummarizationSetBy = Automatic

	column M09
		dataType: string
		lineageTag: 41672e1d-15ac-487d-8905-d2fdeb124614
		summarizeBy: none
		sourceColumn: M09

		annotation SummarizationSetBy = Automatic

	column M10
		dataType: string
		lineageTag: 3e5bbe3e-604b-4648-8247-cf87e496e514
		summarizeBy: none
		sourceColumn: M10

		annotation SummarizationSetBy = Automatic

	column M11
		dataType: string
		lineageTag: c77c6e32-03e3-44df-8b2c-c26788c4a911
		summarizeBy: none
		sourceColumn: M11

		annotation SummarizationSetBy = Automatic

	column M12
		dataType: string
		lineageTag: c6adda5b-601f-4bbf-8a64-f8880be7f8e6
		summarizeBy: none
		sourceColumn: M12

		annotation SummarizationSetBy = Automatic

	partition ResellerSalesTargets = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Student\Downloads\01-prepare-data\ResellerSalesTargets.csv"),[Delimiter=",", Columns=14, Encoding=1200, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}, {"EmployeeID", Int64.Type}, {"M01", type text}, {"M02", type text}, {"M03", type text}, {"M04", type text}, {"M05", type text}, {"M06", type text}, {"M07", type text}, {"M08", type text}, {"M09", type text}, {"M10", type text}, {"M11", type text}, {"M12", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

