table ResellerSalesTargets
	lineageTag: 183130ef-f9ec-41ff-a600-826b16b67b3e

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3a3f126a-cd48-4e5c-bf66-4509b1668e2a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: 149da09f-2fb6-440b-869b-620eab4ed5d5
		summarizeBy: count
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column M01
		dataType: string
		lineageTag: 16d56290-78d2-4d82-8eb6-ad53abe25b73
		summarizeBy: none
		sourceColumn: M01

		annotation SummarizationSetBy = Automatic

	column M02
		dataType: string
		lineageTag: e8295422-2cde-4544-a532-dfb54406f2c4
		summarizeBy: none
		sourceColumn: M02

		annotation SummarizationSetBy = Automatic

	column M03
		dataType: string
		lineageTag: 8abbafd8-2450-48bd-a036-7901d530399a
		summarizeBy: none
		sourceColumn: M03

		annotation SummarizationSetBy = Automatic

	column M04
		dataType: string
		lineageTag: 82c73706-e20c-4da3-8f99-4afab6ec89a4
		summarizeBy: none
		sourceColumn: M04

		annotation SummarizationSetBy = Automatic

	column M05
		dataType: string
		lineageTag: 996dde15-d439-44cc-9691-0b12a6ee5fce
		summarizeBy: none
		sourceColumn: M05

		annotation SummarizationSetBy = Automatic

	column M06
		dataType: string
		lineageTag: 2ec7176c-972a-48ad-96b1-cb75a5f2bd07
		summarizeBy: none
		sourceColumn: M06

		annotation SummarizationSetBy = Automatic

	column M07
		dataType: string
		lineageTag: 50664368-8938-4570-91bf-24a6431bf32f
		summarizeBy: none
		sourceColumn: M07

		annotation SummarizationSetBy = Automatic

	column M08
		dataType: string
		lineageTag: d4659666-928e-4f2c-b1c9-4372022af030
		summarizeBy: none
		sourceColumn: M08

		annotation SummarizationSetBy = Automatic

	column M09
		dataType: string
		lineageTag: 5747aca3-c3dc-46bb-8d92-840b8e1048eb
		summarizeBy: none
		sourceColumn: M09

		annotation SummarizationSetBy = Automatic

	column M10
		dataType: string
		lineageTag: 2ddb95e4-30a3-4e08-8c81-51f1f8ae96ba
		summarizeBy: none
		sourceColumn: M10

		annotation SummarizationSetBy = Automatic

	column M11
		dataType: string
		lineageTag: 474a3d4d-7429-4026-b96f-38a81c805740
		summarizeBy: none
		sourceColumn: M11

		annotation SummarizationSetBy = Automatic

	column M12
		dataType: string
		lineageTag: d4bc10dc-14ab-4b2c-971d-5bcd727f2fab
		summarizeBy: none
		sourceColumn: M12

		annotation SummarizationSetBy = Automatic

	partition ResellerSalesTargets = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Student\Downloads\01-get-data\ResellerSalesTargets.csv"),[Delimiter=",", Columns=14, Encoding=1200, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}, {"EmployeeID", Int64.Type}, {"M01", type text}, {"M02", type text}, {"M03", type text}, {"M04", type text}, {"M05", type text}, {"M06", type text}, {"M07", type text}, {"M08", type text}, {"M09", type text}, {"M10", type text}, {"M11", type text}, {"M12", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

